#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
index:
    path: /login
    controller: App\Wine\Infrastructure\EntryPoint\Controller\PostLoginController
    methods: POST
